### ISSUE TITLE
Inconsistent behavior

### ISSUE THREAD

**Issue by nkostadinov** [2amigos/yii2-resource-manager-component#8]
The two types of resource managers are not completely consistent the way they save files. I currently upload the file content via rest API and I have the string which is the content of the file. In S3 case I do this 

        if(\Yii::$app->resourceManager->save($post, $hash . ".jpg", [
            'Body' => $post,
            'Content-Type' => 'image/jpeg'
        ] ))

So the value of 'Body' is used as the file content. But this doesn't work in the file resource manager case. which means that both classes are not completely replaceable by each other.

**Comment by tonydspaniard** [comment]
are you sure you would be able to do that with S3? What the function expects is an Uploaded file: https://github.com/2amigos/yii2-resource-manager-component/blob/master/AmazonS3ResourceManager.php#L71 how are you doing that? 

I believe the only way to do it is by getting access to the S3 client: 

```php 
\Yii::$app->resourceManager->getClient()->putObject([...]);
```

**Comment by nkostadinov** [comment]
Yes I see, but it's not enforcing it. Anyway in my case it's not working well because I have the file content in string only, and I think it's pointless create file just for this to work, if you have a simple check if 'Body' is present to create that file just like it's possible with S3.

**Comment by tonydspaniard** [comment]
`public function save(UploadedFile $file, $name, $options = [])` would enforce it? Is not about creating a file, is to handle the uploaded file from a form post.

**Comment by nkostadinov** [comment]
Ok, Tony may be this is not the extension for my use case beacuse I do not have uploaded file. I just found https://github.com/creocoder/yii2-flysystem and it's exactly fitting in my case. I think we can close the issue.
